version: '3.9'
services:
  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=8CCA6B60A3EF40A59128@6D2824C9AEDC
      - MSSQL_PID=Developer
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC
    ports:
      - "127.0.0.1:5012:1433"  # Bind only to host's loopback interface
    networks:
      - app-network
    volumes:
      - ./data/mssql/backups:/var/opt/mssql/backups
      - ./data/mssql/data:/var/opt/mssql/data
      - ./data/mssql/log:/var/opt/mssql/log
    restart: unless-stopped
  # MinIO File Storage
  shifty_minio_fileDb:
    container_name: shifty_minio_fileDb
    image: docker.io/bitnami/minio
    ports:
      - '127.0.0.1:9000:9000'  # Bind only to host's loopback interface
      - '127.0.0.1:9001:9001'
    networks:
      - app-network
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=AminShifty1382
      - MINIO_ROOT_PASSWORD=AminShifty1382403
    restart: unless-stopped
    
  
  shifty_aspire-service:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard
    container_name: shifty_aspire-service
    ports:
      - "18888:18888"
      - "4317:18889"
    networks:
      - app-network
    environment:
    - ASPIRE_DASHBOARD_USERNAME=AminShifty1382
    - ASPIRE_DASHBOARD_PASSWORD=AminShifty1382403
    - DASHBOARD__OTLP__AUTHMODE=ApiKey
    - DASHBOARD__OTLP__PRIMARYAPIKEY=FC83FFEF-1C71-4C88-97D7-27CE9570F131
    restart: unless-stopped
           #shiftybacj.ir 
  # Shifty API
  shifty_api:
    build:
      dockerfile: src/Web/Api/Dockerfile
    container_name: shifty_api
    ports:
      - "192.168.10.155:5011:443"
      - "192.168.10.155:5010:8080"
      - "5021:443"
      - "5020:8080"
    depends_on:
      - sqlserver
      - shifty_minio_fileDb
      - shifty_aspire-service
    networks:
      - app-network
    volumes:
      - ./data/Web/app:/app
      - ./data/Web/scr:/src
    restart: always

networks:
  app-network:
    driver: bridge