version: '3.9'

services:
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC
    ports:
      - "5012:1433"
    networks:
      - app-network
    volumes:
      - ${BASE_PATH}/mssql/backups:/var/opt/mssql/backups:rw
      - ${BASE_PATH}/mssql/data:/var/opt/mssql/data:rw
      - ${BASE_PATH}/mssql/log:/var/opt/mssql/log:rw
    restart: unless-stopped
    user: "10001"

  shiftyMinioFileDb:
    container_name: shiftyMinioFileDb
    image: docker.io/bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    volumes:
      - ${BASE_PATH}/minio:/data:rw,z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ${CONFIG}/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
    networks:
      - app-network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ${CONFIG}/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - shifty
    networks:
      - app-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "1888:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=true
      - GF_SERVER_ROOT_URL=https://grafana.mrshift.ir/
      - GF_SERVER_DOMAIN=grafana.mrshift.ir
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ${CONFIG}/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ${CONFIG}/dashboards:/var/lib/grafana/dashboards
      - ${CONFIG}/dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
    depends_on:
      - prometheus
      - loki
    networks:
      - app-network
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network
    restart: unless-stopped

  shifty:
    build:
      dockerfile: src/Web/Api/Dockerfile
    container_name: shifty
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer ${OTEL_SECRET_TOKEN}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - sqlserver
      - shiftyMinioFileDb
      - loki
    networks:
      - app-network
    ports:
      - "1880:8080"
    restart: always

networks:
  app-network:
    driver: bridge

