version: '3.9'

services:
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC
    ports:
      - "5012:1433"
    networks:
      - app-network
    volumes:
      - ${BASE_PATH}/mssql/backups:/var/opt/mssql/backups:rw
      - ${BASE_PATH}/mssql/data:/var/opt/mssql/data:rw
      - ${BASE_PATH}/mssql/log:/var/opt/mssql/log:rw
    restart: unless-stopped
    user: "10001"

  shiftyMinioFileDb:
    container_name: shiftyMinioFileDb
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    volumes:
      - ${BASE_PATH}/minio:/data:rw,z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    restart: unless-stopped
  
  shiftyAspireService:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: shiftyAspireService
    ports:
      - "1888:18888"
      - "4317:18889"
    networks:
      - app-network
    environment:
      - ASPIRE_DASHBOARD_USERNAME=AminShifty1382
      - ASPIRE_DASHBOARD_PASSWORD=AminShifty1382403
      - DASHBOARD__OTLP__AUTHMODE=ApiKey
      - DASHBOARD__OTLP__PRIMARYAPIKEY=FC83FFEF-1C71-4C88-97D7-27CE9570F131
    restart: unless-stopped
  
  
  
  shifty:
    build:
      dockerfile: src/Web/Api/Dockerfile
    container_name: shifty
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4317
      - OTEL_SERVICE_NAME=Shifty
    depends_on:
      - sqlserver
      - shiftyMinioFileDb
    networks:
      - app-network
    ports:
      - "1880:8080"
    restart: always

networks:
  app-network:
    driver: bridge
