version: '3.9'
services:
  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=8CCA6B60A3EF40A59128@6D2824C9AEDC
      - MSSQL_PID=Developer
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC
    ports:
      - "5012:1433"
    networks:
      - app-network
    volumes:
      - ./data/mssql/backups:/var/opt/mssql/backups
      - ./data/mssql/data:/var/opt/mssql/data
      - ./data/mssql/log:/var/opt/mssql/log
    restart: unless-stopped

  # MinIO File Storage
  shiftyMinioFileDb:
    container_name: shiftyMinioFileDb
    image: docker.io/bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - app-network
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=AminShifty1382
      - MINIO_ROOT_PASSWORD=AminShifty1382403
    restart: unless-stopped

  # Aspire Service
  shiftyAspireService:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: shiftyAspireService
    ports:
      - "18888:18888"
      - "4317:18889"
    networks:
      - app-network
    environment:
      - ASPIRE_DASHBOARD_USERNAME=AminShifty1382
      - ASPIRE_DASHBOARD_PASSWORD=AminShifty1382403
      - DASHBOARD__OTLP__AUTHMODE=ApiKey
      - DASHBOARD__OTLP__PRIMARYAPIKEY=FC83FFEF-1C71-4C88-97D7-27CE9570F131
    restart: unless-stopped

  # Reverse Proxy
  reverse-proxy:
    image: nginxproxy/nginx-proxy
    container_name: reverse-proxy
    ports:
      - "1880:80"
      - "1443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # Shifty API
  shifty.api:
    build:
      dockerfile: src/Web/Api/Dockerfile
    container_name: shifty.api
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4317
      - OTEL_SERVICE_NAME=Shifty
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5021:443"
      - "5020:8080"
    depends_on:
      - sqlserver
      - shiftyMinioFileDb
      - shiftyAspireService
    networks:
      - app-network
    volumes:
      - ./data/Web/app:/app
    restart: always

networks:
  app-network:
    driver: bridge
