version: '3.9'

services:
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC
    ports:
      - "5012:1433"
    networks:
      - app-network
    volumes:
      - ${BASE_PATH}/mssql/backups:/var/opt/mssql/backups:rw
      - ${BASE_PATH}/mssql/data:/var/opt/mssql/data:rw
      - ${BASE_PATH}/mssql/log:/var/opt/mssql/log:rw
    restart: unless-stopped
    user: "10001"

  shiftyMinioFileDb:
    container_name: shiftyMinioFileDb
    image: docker.io/bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    volumes:
      - ${BASE_PATH}/minio:/data:rw,z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ${CONFIG}/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OpenTelemetry Tracing (gRPC)
      - "4318:4318" # OpenTelemetry Tracing (HTTP)
      - "9464:9464" # Prometheus Metrics
    networks:
     - app-network
    restart: always
    depends_on:
      - seq

  seq:
    image: datalust/seq
    container_name: seq
    ports:
      - "1888:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_ADMIN_PASSWORD} # Sets admin password
      - SEQ_STORAGE_PASSWORDHASHING=PBKDF2 # Enables secure password hashing
      - SEQ_LOGGING__FILESIZE=200000000  # ✅ Limit log file size to 200MB (200 * 1024 * 1024 bytes)
      - SEQ_LOGGING__FILECOUNT=3  # ✅ Keep a maximum of 3 log files
    volumes:
      - ${BASE_PATH}/seq:/data
    networks:
      - app-network
    restart: unless-stopped
  
  
  shifty:
    build:
      dockerfile: src/Web/Api/Dockerfile
    container_name: shifty
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - sqlserver
      - shiftyMinioFileDb
      - seq
    networks:
      - app-network
    ports:
      - "1880:8080"
    restart: always

networks:
  app-network:
    driver: bridge
