version: '3.9'
services:
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_LCID=1033
      - TZ=Etc/UTC
    ports:
      - "5012:1433"
    networks:
      - app-network
    volumes:
      - ${BASE_PATH}/mssql/backups:/var/opt/mssql/backups:rw,z
      - ${BASE_PATH}/mssql/data:/var/opt/mssql/data:rw,z
      - ${BASE_PATH}/mssql/log:/var/opt/mssql/log:rw,z
    restart: unless-stopped

  shiftyMinioFileDb:
    container_name: shiftyMinioFileDb
    image: docker.io/bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - app-network
    volumes:
      - ${BASE_PATH}/minio:/data:rw,z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    restart: unless-stopped

  shiftyAspireService:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    container_name: shiftyAspireService
    ports:
      - "18888:18888"
      - "4317:18889"
    networks:
      - app-network
    hostname: "ipalytics.ir"
    environment:
      - ASPIRE_DASHBOARD_USERNAME=${ASPIRE_DASHBOARD_USERNAME}
      - ASPIRE_DASHBOARD_PASSWORD=${ASPIRE_DASHBOARD_PASSWORD}
      - DASHBOARD__OTLP__AUTHMODE=ApiKey
      - DASHBOARD__OTLP__PRIMARYAPIKEY=FC83FFEF-1C71-4C88-97D7-27CE9570F131
      - VIRTUAL_HOST=ipalytics.ir

    restart: unless-stopped


  shifty.api:
    build:
      dockerfile: src/Web/Api/Dockerfile
    container_name: shifty.api
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
    depends_on:
      - sqlserver
      - shiftyMinioFileDb
      - shiftyAspireService
    networks:
      - app-network
    ports:
      - ${PORT_API_EXTERNAL}:${PORT_API_INTERNAL}
    restart: always

networks:
  app-network:
    driver: bridge
