//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shifty.ApiFramework.Resources.Middleware.Tenant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TenantValidationMiddleware_fa_IR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TenantValidationMiddleware_fa_IR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shifty.ApiFramework.Resources.Middleware.Tenant.TenantValidationMiddleware.fa-IR", typeof(TenantValidationMiddleware_fa_IR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دستگاه مشخص نشده است..
        /// </summary>
        internal static string Device_type_is_missing_ {
            get {
                return ResourceManager.GetString("Device type is missing.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطمینان حاصل کنید که هدر &apos;X-Device-Type&apos; در درخواست گنجانده شده است..
        /// </summary>
        internal static string Ensure_that__X_Device_Type__header_is_included_in_the_request_ {
            get {
                return ResourceManager.GetString("Ensure that \'X-Device-Type\' header is included in the request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطمینان حاصل کنید که شناسه مستأجر در درخواست ارائه شده است..
        /// </summary>
        internal static string Ensure_that_the_tenant_ID_is_provided_in_the_request_ {
            get {
                return ResourceManager.GetString("Ensure that the tenant ID is provided in the request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستأجر یافت نشد..
        /// </summary>
        internal static string Tenant_not_found_ {
            get {
                return ResourceManager.GetString("Tenant not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامترهای مستأجر وجود ندارد..
        /// </summary>
        internal static string Tenant_parameters_are_missing_ {
            get {
                return ResourceManager.GetString("Tenant parameters are missing.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستأجر درخواست‌شده وجود ندارد..
        /// </summary>
        internal static string The_requested_tenant_does_not_exist_ {
            get {
                return ResourceManager.GetString("The requested tenant does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اعتبارسنجی.
        /// </summary>
        internal static string Validation_Error {
            get {
                return ResourceManager.GetString("Validation Error", resourceCulture);
            }
        }
    }
}
