//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shifty.Api.Resources.Filters {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiExceptionFilter_fa_IR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiExceptionFilter_fa_IR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tenant.Api.Resources.Filters.ApiExceptionFilter.fa-IR", typeof(ApiExceptionFilter_fa_IR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای داخلی سرور..
        /// </summary>
        internal static string Internal_Server_Error_ {
            get {
                return ResourceManager.GetString("Internal Server Error.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یافت نشد..
        /// </summary>
        internal static string Not_Found_ {
            get {
                return ResourceManager.GetString("Not Found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منبع مورد نظر یافت نشد..
        /// </summary>
        internal static string The_requested_resource_was_not_found_ {
            get {
                return ResourceManager.GetString("The requested resource was not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرمجاز..
        /// </summary>
        internal static string Unauthorized_ {
            get {
                return ResourceManager.GetString("Unauthorized.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات اعتبارسنجی..
        /// </summary>
        internal static string Validation_details_ {
            get {
                return ResourceManager.GetString("Validation details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اعتبارسنجی..
        /// </summary>
        internal static string Validation_Error_ {
            get {
                return ResourceManager.GetString("Validation Error.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به انجام این عملیات نیستید..
        /// </summary>
        internal static string You_are_not_authorized_to_perform_this_action_ {
            get {
                return ResourceManager.GetString("You are not authorized to perform this action.", resourceCulture);
            }
        }
    }
}
