receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:  # Replaces deprecated "logging" exporter
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp:
    endpoint: "http://prometheus:4317"
    tls:
      insecure: true 
 

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, otlp  ]  # Changed "logging" to "debug"
    metrics:
      receivers: [ otlp ]
      exporters: [ rometheus  ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug]  # Changed "logging" to "debug"
