global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'shifty-metrics'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: [ 'shifty:8080' ]

  - job_name: 'shifty-health'
    metrics_path: '/api/health'
    static_configs:
      - targets: [ 'shifty:8080' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
      
      
  - job_name: 'otel-collector'
    scrape_interval: 5s  # ✅ Lower interval for detailed tracing
    static_configs:
      - targets: [ 'otel-collector:8889' ]  # Metrics
      - targets: [ 'otel-collector:13133' ] # Health
      